# Generated by Django 6.0.4 on 2026-08-11 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Editoriales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AutorRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('PRINCIPAL', 'Autor principal'), ('COAUTOR', 'Coautor'), ('EDITOR', 'Editor'), ('TRADUCTOR', 'Traductor'), ('COMPILADOR', 'Compilador')], default='PRINCIPAL', max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.autor')),
            ],
            options={
                'verbose_name': 'Autor de registro',
                'verbose_name_plural': 'Autores de registro',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RegistroBibliografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('edicion', models.CharField(blank=True, max_length=100)),
                ('anio_publicacion', models.PositiveIntegerField(blank=True, null=True)),
                ('lugar_publicacion', models.CharField(blank=True, max_length=150)),
                ('idioma', models.CharField(blank=True, default='Español', max_length=50)),
                ('descripcion_fisica', models.CharField(blank=True, max_length=200)),
                ('clasificacion', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('marc_xml', models.TextField(blank=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('autores', models.ManyToManyField(related_name='registros', through='catalogo.AutorRegistro', to='catalogo.autor')),
                ('editorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='catalogo.editorial')),
                ('materias', models.ManyToManyField(blank=True, related_name='registros', to='catalogo.materia')),
            ],
            options={
                'verbose_name': 'Registro bibliográfico',
                'verbose_name_plural': 'Registros bibliográficos',
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('PERDIDO', 'Perdido'), ('REPARACION', 'En reparación')], default='DISPONIBLE', max_length=20)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='catalogo.registrobibliografico')),
            ],
        ),
        migrations.AddField(
            model_name='autorregistro',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.registrobibliografico'),
        ),
        migrations.AlterUniqueTogether(
            name='autorregistro',
            unique_together={('registro', 'autor')},
        ),
    ]
