# Generated by Django 6.0.4 on 2026-08-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(help_text="Formato recomendado: 'Apellido, Nombre' — se usa tal cual en los campos MARC 100/700.", max_length=200),
        ),
    ]
