# Generated by Django 6.0.4 on 2026-08-11 14:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_autor_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstanciaDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Constancia de donación',
                'verbose_name_plural': 'Constancias de donación',
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='ConstanciaDonacionLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('constancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='catalogo.constanciadonacion')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.registrobibliografico')),
            ],
            options={
                'verbose_name': 'Libro de constancia',
                'verbose_name_plural': 'Libros de constancia',
                'unique_together': {('constancia', 'registro')},
            },
        ),
    ]
