# Generated by Django 6.0.4 on 2026-08-14 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0016_mantenimiento_todos_los_permisos'),
        ('catalogo', '0005_permiso_constancialibro_bibliotecario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrobibliografico',
            name='alumno',
            field=models.OneToOneField(blank=True, help_text='Alumno que dio de alta este libro desde el cuestionario de registro (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_bibliografico', to='alumnos.alumno'),
        ),
    ]
