# Generated by Django 6.0.4 on 2026-07-10 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0011_alter_alumno_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDeteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('robo', 'Posible sustracción de libro'), ('ruptura', 'Posible ruptura de páginas')], max_length=20)),
                ('fuente', models.CharField(help_text='Nombre de la cámara que generó el evento', max_length=100)),
                ('confianza', models.FloatField(help_text='Confianza del modelo/heurística (0.0 a 1.0)')),
                ('imagen_evidencia', models.ImageField(upload_to='detecciones/%Y/%m/')),
                ('clip_evidencia', models.FileField(blank=True, null=True, upload_to='detecciones/clips/%Y/%m/')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Evento detectado',
                'verbose_name_plural': 'Eventos detectados',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
