# Generated by Django 6.0.4 on 2026-08-11 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0013_crear_grupos_roles'),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DEVUELTO', 'Devuelto'), ('PERDIDO', 'Perdido')], default='ACTIVO', max_length=20)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='alumnos.alumno')),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='catalogo.ejemplar')),
            ],
            options={
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
