# Generated by Django 6.0.4 on 2026-08-11 04:17

import circulacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(default=circulacion.models._vencimiento_por_defecto),
        ),
    ]
