# Generated by Django 6.0.4 on 2026-08-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulacion', '0002_alter_prestamo_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='dias_retraso',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='multa_cobrada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='multa_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='multa_pagada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='multa_pagada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='multa_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
