# Generated by Django 6.0.4 on 2026-08-14 16:10

import circulacion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_registrobibliografico_alumno'),
        ('circulacion', '0004_borrar_prestamos_existentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='ejemplar',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='alumno_nombre',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre del alumno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='carrera',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_salida',
            field=models.DateField(default=circulacion.models._salida_por_defecto, verbose_name='Fecha de salida'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='folio',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='matricula',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(default=circulacion.models._devolucion_por_defecto, verbose_name='Fecha de devolución'),
        ),
        migrations.CreateModel(
            name='PrestamoLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_folio', to='catalogo.ejemplar')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='circulacion.prestamo')),
            ],
            options={
                'unique_together': {('prestamo', 'ejemplar')},
            },
        ),
    ]
