# Generated by Django 6.0.3 on 2026-03-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('carrera', models.CharField(max_length=100)),
                ('semestre', models.IntegerField()),
                ('documento', models.FileField(upload_to='documentos/')),
            ],
        ),
    ]
