# Generated by Django 6.0.3 on 2026-03-29 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='documento',
            new_name='documentos',
        ),
    ]
