# Generated by Django 6.0.3 on 2026-03-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_remove_alumno_documentos_alumno_documento1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='documento1',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='documento2',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='documento3',
        ),
        migrations.AddField(
            model_name='alumno',
            name='documento',
            field=models.FileField(default='documentos/default.pdf', upload_to='documentos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='semestre',
            field=models.IntegerField(),
        ),
    ]
