# Generated by Django 6.0.3 on 2026-03-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_remove_alumno_documento1_remove_alumno_documento2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='documento',
        ),
        migrations.AddField(
            model_name='alumno',
            name='documento1',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='documento2',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='documento3',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(choices=[('MEDICO', 'Médico Cirujano'), ('NUTRICION', 'Nutrición'), ('FISIO', 'Fisioterapia'), ('OCUPACIONAL', 'Terapia Ocupacional'), ('BIOING', 'Bioingeniería Médica')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='semestre',
            field=models.IntegerField(choices=[(1, '1°'), (2, '2°'), (3, '3°'), (4, '4°'), (5, '5°'), (6, '6°'), (7, '7°'), (8, '8°')]),
        ),
    ]
