# Generated by Django 6.0.3 on 2026-03-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_fix_columnas'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='acepta_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='director',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('ARTICULO', 'Artículo especializado para publicar en revista indizada'), ('CREDITOS', 'Créditos en Estudios Avanzados'), ('ENSAYO', 'Ensayo'), ('TESIS', 'Tesis'), ('TESINA', 'Tesina'), ('REPORTE_CONOCIMIENTOS', 'Reporte de aplicación de conocimientos'), ('REPORTE_SOCIAL', 'Reporte de servicio social en el Área de la Salud'), ('REPORTE_RESIDENCIA', 'Reporte de residencia de investigación')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(choices=[('MEDICO', 'Lic. Médico Cirujano'), ('NUTRICION', 'Lic. Nutrición'), ('FISIO', 'Lic. Fisioterapia'), ('OCUPACIONAL', 'Lic. Terapia Ocupacional'), ('BIOING', 'Lic.Bioingeniería Médica')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En revisión', 'En revisión'), ('Revisado', 'Revisado'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
    ]
