# Generated by Django 6.0.3 on 2026-04-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_alumno_acepta_terminos_alumno_correo_alumno_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='facultad',
            field=models.CharField(choices=[('MEDICINA', 'Facultad de Medicina'), ('QUIMICA', 'Facultad de Química')], default='MEDICINA', max_length=20),
        ),
    ]
