# Generated by Django 6.0.3 on 2026-04-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_alumno_facultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
