# Generated by Django 6.0.3 on 2026-05-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_alumno_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='semestre',
            field=models.IntegerField(blank=True, choices=[(1, '1°'), (2, '2°'), (3, '3°'), (4, '4°'), (5, '5°'), (6, '6°'), (7, '7°'), (8, '8°')], null=True),
        ),
    ]
