# Generated by Django 6.0.3 on 2026-05-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_alter_alumno_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(choices=[('MEDICO', 'Lic. Médico Cirujano'), ('NUTRICION', 'Lic. Nutrición'), ('FISIO', 'Lic. Fisioterapia'), ('OCUPACIONAL', 'Lic. Terapia Ocupacional'), ('BIOING', 'Lic. Bioingeniería Médica'), ('QUIMICA', 'Lic. Química'), ('QUIM_FARM', 'Lic. Química Farmacéutica Biológica'), ('QUIM_ALIM', 'Lic. Química en Alimentos'), ('ING_QUIM', 'Lic. Ingeniería Química'), ('ING_PETRO', 'Lic. Ingeniería Petroquímica')], max_length=20),
        ),
    ]
