# Generated by Django 6.0.4 on 2026-08-11 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0011_alter_alumno_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpresionConstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NO_ADEUDO', 'Constancia No Adeudo'), ('REGISTRO_MATERIAL', 'Registro Material'), ('CARTA_AUTORIZACION', 'Carta Autorización')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.alumno')),
            ],
        ),
    ]
