# Generated by Django 6.0.4 on 2026-08-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0014_crear_grupo_bibliotecario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='libro_autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='libro_edicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='libro_editorial',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='libro_portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='libro_titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
